---

- name: combine vpc filter
  set_fact:
    _aws_vpc_dhcp_vpc_filter: |
      {{
        aws_vpc_dhcp_vpc_filter_additional + dhcp_options_set.vpc_filter
      }}

- name: gather vpc facts by filter
  ec2_vpc_net_facts:
    aws_access_key: "{{ lookup('ENV', 'AWS_ACCESS_KEY') | default(omit) }}"
    aws_secret_key: "{{ lookup('ENV', 'AWS_SECRET_KEY') | default(omit)  }}"
    security_token: "{{ lookup('ENV', 'AWS_SECURITY_TOKEN') | default(omit) }}"
    profile: "{{ aws_vpc_dhcp_profile | default(omit) }}"
    region: "{{ dhcp_options_set.region | default(aws_vpc_dhcp_default_region) }}"
    filters: "{{ _aws_vpc_dhcp_vpc_filter | get_attr('key', 'val') }}"
  register: _vpc_dhcp_vpc

- name: fail if vpc was not found
  assert:
    that:
      - _vpc_dhcp_vpc.vpcs is defined
      - _vpc_dhcp_vpc.vpcs | length == 1
    msg: Not exactly one VPC has been found

- name: set vpc id
  set_fact:
    aws_vpc_dhcp_vpc_id: "{{ _vpc_dhcp_vpc.vpcs[0].id }}"

- name: set vpc cidr
  set_fact:
    aws_vpc_dhcp_vpc_cidr: "{{ _vpc_dhcp_vpc.vpcs[0].cidr_block }}"
